server:
  port: 9090
spring:
  application:
    name: 241DSWSpringMSDemo01User
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/usuario
    username: miguel
    password: UU0yR8VpR55ppwnBD6QgFFh49RBYkFVO
  jpa:
    hibernate:
      ddl-auto: create
    #database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect      
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
