server:
  port: 8090

spring:
  application:
    name: 241DSWSpringMSDemo01Pepple
    
  config:
    import: optional:configserver:http://localhost:8888
    
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Persona
    username: postgres
    password: Ryback22
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
    
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
